trigger: none

pr:
  branches:
    include:
      - ci_add_main

pool:
  vmImage: windows-2019
- name: Repos
  type: object
  default:
    - azure-sdk-for-android
    - azure-sdk-for-c
    - azure-sdk-for-cpp
    - azure-sdk-for-go
    - azure-sdk-for-ios
    - azure-sdk-for-java
    - azure-sdk-for-js
    - azure-sdk-for-net
    - azure-sdk-for-python
jobs:
  - job: AddMainBranch
    pool:
      vmImage: windows-2019
      - ${{ each repo in parameters.Repos }}:
        steps:
        - task: PowerShell@2
          displayName: 'Add main in ci yaml'
          inputs:
            pwsh: true
            filePath: $(Build.SourcesDirectory)/eng/common/scripts/add_main.ps1 
            arguments: >
              -repo: "${{ parameters.Repos }}"
        - template: /eng/common/pipelines/templates/steps/create-pull-request.yml
          parameters:
            RepoName: 'Azure'
            RepoOwner: "${{ parameters.Repo }}"
            PRBranchName: 'add_main'
            CommitMsg: "Added main branch under trigger and pr in ci yml."
            PRTitle: "Added main branch under trigger and pr in ci yml."
            BaseBranchName: 'master'